export { default as HomeLayout } from "./HomeLayout";
export { default as Dashboard } from "./Dashboard";
export { default as Analytics } from "./Analytics";
export { default as Collections } from "./Collections";
export { default as Messages } from "./Messages";
export { default as Users } from "./Users";
export { default as Account } from "./Account";
export { default as Settings } from "./Settings";
export { default as Logout } from "./Logout";
